services:
  eventhopper:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - mongo-container
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run start:dev

  postgres-container:
    container_name: postgres-container
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    env_file:
      - ./.env

  mongo-container:
    container_name: mongo-container
    image: mongo
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./.env

  redis-container:
    container_name: redis-container
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    env_file:
      - ./.env

  elasticsearch-container:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    ports:
      - "9200:9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    env_file:
      - ./.env


volumes:
  mongo_db:
    external: false
  redis-data:
    external: false
  postgres-data:
    external: false
  elastic-data:
    external: false